namespace ITAdmin.Api.Contracts.NotificationOutbox;

public sealed record NotificationOutboxListItemResponse(
    Guid Id,
    string Channel,
    string ProviderKey,
    string RecipientMasked,
    string? Subject,
    string Status,
    int AttemptCount,
    int MaxAttempts,
    DateTimeOffset? NextAttemptAt,
    DateTimeOffset? LastAttemptAt,
    DateTimeOffset? SentAt,
    string? RelatedModule,
    string? RelatedEvent,
    string? RelatedEntityType,
    string? RelatedEntityId,
    DateTimeOffset CreatedAt,
    string? ProviderSummary,
    string? LastErrorMessage);

public sealed record NotificationOutboxDetailResponse(
    Guid Id,
    string Channel,
    string ProviderKey,
    string RecipientMasked,
    string? Subject,
    string Body,
    string Status,
    int AttemptCount,
    int MaxAttempts,
    DateTimeOffset? NextAttemptAt,
    DateTimeOffset? LastAttemptAt,
    DateTimeOffset? SentAt,
    DateTimeOffset? LockedAt,
    string? LockedBy,
    string? LastErrorMessage,
    string? ProviderSummary,
    string? RelatedModule,
    string? RelatedEvent,
    string? RelatedEntityType,
    string? RelatedEntityId,
    string? CorrelationId,
    DateTimeOffset CreatedAt,
    string? CreatedBy,
    DateTimeOffset? UpdatedAt,
    string? UpdatedBy);
