using System.Text.Json;
using System.Text.Json.Serialization;

namespace ITAdmin.Deployment;

/// <summary>
/// Durable machine secrets for an ITAdmin installation.
///
/// <para>
/// Secrets are not stored in the release artifact, the environment config JSON, the installation
/// state, or IIS <c>applicationHost.config</c> app-pool environment variables. They live under
/// <see cref="DeploymentLayout.SecretsRoot"/> as a single DPAPI-LocalMachine-protected payload,
/// ACL'd to SYSTEM, Administrators, and the app-pool identity.
/// </para>
///
/// <para>
/// LocalMachine DPAPI means any process that can read the file on this machine can decrypt it —
/// including the app pool — without a service-account-specific key. Moving the ciphertext to
/// another machine will not decrypt; restore on a replacement host requires re-entering secrets
/// (or restoring the machine DPAPI state, which is an OS-level concern outside this product).
/// </para>
/// </summary>
public sealed record MachineSecrets
{
    public const int CurrentSchemaVersion = 1;

    /// <summary>Protected payload file name under <c>SecretsRoot</c>.</summary>
    public const string ProtectedFileName = "runtime.secrets.dpapi";

    [JsonPropertyName("schemaVersion")]
    public int SchemaVersion { get; init; } = CurrentSchemaVersion;

    /// <summary>Full Npgsql connection string including the password.</summary>
    [JsonPropertyName("connectionString")]
    public string ConnectionString { get; init; } = string.Empty;

    /// <summary>JWT HMAC signing key (high entropy). Generated by the installer, never chosen.</summary>
    [JsonPropertyName("jwtKey")]
    public string JwtKey { get; init; } = string.Empty;

    /// <summary>
    /// Plaintext first-run setup key, generated by the installer.
    ///
    /// <para>
    /// It is held here so the installer's directory-bootstrap step can drive the application's own
    /// setup service, rather than a second privileged code path that reimplements role assignment.
    /// It authorizes that one internal call; there is no in-application setup wizard. It is never
    /// printed, never logged, and never leaves this store.
    /// </para>
    /// </summary>
    [JsonPropertyName("setupKey")]
    public string SetupKey { get; init; } = string.Empty;

    /// <summary>
    /// <c>sha256:</c>-prefixed hash of <see cref="SetupKey"/>, surfaced to the application as
    /// <c>Setup:SetupKeyHash</c>. The application only ever sees the hash.
    /// </summary>
    [JsonPropertyName("setupKeyHash")]
    public string SetupKeyHash { get; init; } = string.Empty;

    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        WriteIndented = false,
        DefaultIgnoreCondition = JsonIgnoreCondition.Never,
    };

    public string ToJson() => JsonSerializer.Serialize(this, SerializerOptions);

    public static MachineSecrets? FromJson(string? json)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            return null;
        }

        try
        {
            return JsonSerializer.Deserialize<MachineSecrets>(json, SerializerOptions);
        }
        catch (JsonException)
        {
            return null;
        }
    }

    public ConfigValidationResult Validate()
    {
        var errors = new List<string>();

        if (SchemaVersion != CurrentSchemaVersion)
        {
            errors.Add($"Unsupported machine secrets schemaVersion {SchemaVersion}; expected {CurrentSchemaVersion}.");
        }

        if (string.IsNullOrWhiteSpace(ConnectionString))
        {
            errors.Add("connectionString is required.");
        }

        if (string.IsNullOrWhiteSpace(JwtKey))
        {
            errors.Add("jwtKey is required.");
        }
        else if (!GeneratedSecrets.LooksSufficientlyRandom(JwtKey))
        {
            errors.Add("jwtKey does not carry enough entropy to sign tokens with.");
        }

        if (string.IsNullOrWhiteSpace(SetupKey))
        {
            errors.Add("setupKey is required.");
        }
        else if (!GeneratedSecrets.LooksSufficientlyRandom(SetupKey))
        {
            errors.Add("setupKey does not carry enough entropy.");
        }

        if (string.IsNullOrWhiteSpace(SetupKeyHash))
        {
            errors.Add("setupKeyHash is required.");
        }
        else if (!string.IsNullOrWhiteSpace(SetupKey)
                 && !string.Equals(SetupKeyHash, GeneratedSecrets.HashSetupKey(SetupKey), StringComparison.Ordinal))
        {
            errors.Add("setupKeyHash does not match setupKey.");
        }

        return new ConfigValidationResult(errors.Count == 0, errors);
    }
}

/// <summary>
/// Pure interpretation of prerequisite detection results — no Windows side effects.
/// Used by unit tests and mirrored by the installer control flow.
/// </summary>
public static class PrerequisiteLifecycle
{
    public static PrerequisitePlan Plan(
        PrerequisiteDetection detection,
        bool provisionRequested)
    {
        ArgumentNullException.ThrowIfNull(detection);

        if (!detection.HasBlockingGaps)
        {
            return new PrerequisitePlan(
                PrerequisitePlanAction.Continue,
                Array.Empty<string>(),
                RequiresHostingBundleInstall: false,
                RequiresRebootBeforeContinue: detection.RestartPending,
                Message: detection.RestartPending
                    ? "Prerequisites look installed but a restart is still pending; reboot before continuing."
                    : "All required prerequisites are present.");
        }

        if (!provisionRequested)
        {
            return new PrerequisitePlan(
                PrerequisitePlanAction.FailReportOnly,
                detection.MissingIisFeatures.ToArray(),
                RequiresHostingBundleInstall: detection.HostingBundleMissingOrUnusable,
                RequiresRebootBeforeContinue: false,
                Message: "Required prerequisites are missing. Re-run with -ProvisionPrerequisites to install them.");
        }

        if (detection.RestartPending)
        {
            return new PrerequisitePlan(
                PrerequisitePlanAction.StopForReboot,
                Array.Empty<string>(),
                RequiresHostingBundleInstall: false,
                RequiresRebootBeforeContinue: true,
                Message: "A restart is pending from a previous prerequisite change; reboot before provisioning further.");
        }

        if (detection.MissingIisFeatures.Count > 0)
        {
            return new PrerequisitePlan(
                PrerequisitePlanAction.InstallIisFeatures,
                detection.MissingIisFeatures.ToArray(),
                RequiresHostingBundleInstall: false,
                RequiresRebootBeforeContinue: false,
                Message: "Install the missing IIS Windows features, then re-detect.");
        }

        if (detection.HostingBundleMissingOrUnusable)
        {
            return new PrerequisitePlan(
                PrerequisitePlanAction.InstallHostingBundle,
                Array.Empty<string>(),
                RequiresHostingBundleInstall: true,
                RequiresRebootBeforeContinue: false,
                Message: "Install or repair the ASP.NET Core Hosting Bundle, then re-detect.");
        }

        // WebAdministration missing while features claim installed — treat as incomplete IIS tooling.
        return new PrerequisitePlan(
            PrerequisitePlanAction.InstallIisFeatures,
            IisPrerequisiteFeatures.RequiredNames.Where(name =>
                name is "Web-Scripting-Tools" or "Web-Mgmt-Console").ToArray(),
            RequiresHostingBundleInstall: false,
            RequiresRebootBeforeContinue: false,
            Message: "IIS management scripting is unavailable; ensure Web-Scripting-Tools is installed.");
    }

    /// <summary>
    /// After a provision step returns, decide whether to reboot, re-detect, or continue.
    /// </summary>
    public static PrerequisitePlan InterpretProvisionResult(PrerequisiteProvisionResult result)
    {
        ArgumentNullException.ThrowIfNull(result);

        if (!result.Succeeded)
        {
            return new PrerequisitePlan(
                PrerequisitePlanAction.FailReportOnly,
                Array.Empty<string>(),
                RequiresHostingBundleInstall: false,
                RequiresRebootBeforeContinue: false,
                Message: result.Message);
        }

        if (result.RestartNeeded)
        {
            return new PrerequisitePlan(
                PrerequisitePlanAction.StopForReboot,
                Array.Empty<string>(),
                RequiresHostingBundleInstall: false,
                RequiresRebootBeforeContinue: true,
                Message: result.Message);
        }

        return new PrerequisitePlan(
            PrerequisitePlanAction.ReDetect,
            Array.Empty<string>(),
            RequiresHostingBundleInstall: false,
            RequiresRebootBeforeContinue: false,
            Message: "Provision step succeeded; re-run detection before continuing.");
    }
}

public sealed record PrerequisiteDetection(
    IReadOnlyList<string> MissingIisFeatures,
    bool WebAdministrationAvailable,
    bool AncmPresent,
    bool SharedFrameworkSatisfied,
    bool AncmModuleRegistered,
    bool RestartPending,
    bool IisInstalled = true)
{
    /// <summary>
    /// ANCM binary is on disk and the required AspNetCore.App shared framework is present.
    /// Does not imply IIS module registration.
    /// </summary>
    public bool HostingBundlePresent => AncmPresent && SharedFrameworkSatisfied;

    /// <summary>
    /// Shared-framework major matches the app TFM. Kept as a named alias so older call sites and
    /// tests that spoke of "version satisfied" remain readable - this is NOT ANCM file version.
    /// </summary>
    public bool HostingBundleVersionSatisfied => SharedFrameworkSatisfied;

    public bool HostingBundleUsable =>
        AspNetCoreHostingBundleRequirement.IsHostingUsable(
            AncmPresent,
            SharedFrameworkSatisfied,
            IisInstalled,
            WebAdministrationAvailable,
            AncmModuleRegistered);

    public bool HostingBundleMissingOrUnusable => !HostingBundleUsable;

    public bool HasBlockingGaps =>
        MissingIisFeatures.Count > 0
        || !WebAdministrationAvailable
        || HostingBundleMissingOrUnusable
        || RestartPending;

    /// <summary>
    /// Operator-facing diagnosis lines. Built with concatenation (never composite format inside
    /// collection.Add) so a placeholder mismatch cannot replace the real prerequisite error.
    /// </summary>
    public IReadOnlyList<string> FormatHostingBlockingProblems(
        string displayName,
        string installerFileNamePattern,
        string ancmModuleName,
        string? ancmVersionText = null)
    {
        if (HostingBundleUsable)
        {
            return Array.Empty<string>();
        }

        if (!AncmPresent)
        {
            return
            [
                displayName + " is not installed (ASP.NET Core Module V2 was not found). " +
                "Provide an offline installer via -HostingBundlePath (or prerequisites\\" +
                installerFileNamePattern + ") and re-run with -ProvisionPrerequisites."
            ];
        }

        if (!SharedFrameworkSatisfied)
        {
            return
            [
                displayName + " is incomplete: Microsoft.AspNetCore.App " +
                AspNetCoreHostingBundleRequirement.MajorVersion +
                ".x was not found under Program Files\\dotnet\\shared. " +
                "Install or repair the Hosting Bundle, then re-detect."
            ];
        }

        if (IisInstalled && WebAdministrationAvailable && !AncmModuleRegistered)
        {
            return
            [
                "ASP.NET Core Module '" + ancmModuleName +
                "' is not registered with IIS. The Hosting Bundle must be installed or repaired after IIS."
            ];
        }

        var ancmLabel = string.IsNullOrWhiteSpace(ancmVersionText) ? "unknown" : ancmVersionText;
        return
        [
            displayName + " is present (ANCM " + ancmLabel +
            ") but was not classified as usable. Re-run detection after verifying the shared framework and IIS module registration."
        ];
    }

    public string FormatHostingDetectionDetail()
    {
        var ancmLabel = "ANCM present";
        if (!AncmPresent)
        {
            return "ASP.NET Core Hosting Bundle missing or incomplete (ANCM not found)";
        }

        if (HostingBundleUsable)
        {
            return "ASP.NET Core Hosting Bundle usable (" + ancmLabel +
                   ", sharedFrameworkOk=True, moduleRegistered=" + AncmModuleRegistered + ")";
        }

        return "Hosting Bundle present but not usable (" + ancmLabel +
               ", sharedFrameworkOk=" + SharedFrameworkSatisfied +
               ", moduleRegistered=" + AncmModuleRegistered + ")";
    }
}


public sealed record PrerequisiteProvisionResult(bool Succeeded, bool RestartNeeded, string Message);

public sealed record PrerequisitePlan(
    PrerequisitePlanAction Action,
    IReadOnlyList<string> FeaturesToInstall,
    bool RequiresHostingBundleInstall,
    bool RequiresRebootBeforeContinue,
    string Message);

public enum PrerequisitePlanAction
{
    Continue,
    FailReportOnly,
    InstallIisFeatures,
    InstallHostingBundle,
    ReDetect,
    StopForReboot,
}
