namespace ITAdmin.Api.Contracts.AdManagement;

public sealed record AdManagementSettingsResponse(
    bool IsConfigured,
    bool IsEnabled,
    string? DomainFqdn,
    string? DefaultUserCreationUpnSuffix,
    string? DefaultUserOu,
    string? DefaultGroupOu,
    string? DefaultComputerOu,
    string? NetbiosDomainName,
    string? DefaultNamingContext,
    string? BaseDn,
    string? UsersRootOu,
    string? DisabledUsersOu,
    string? GroupsSearchBase,
    string? ComputersSearchBase,
    IReadOnlyList<string> PreferredDomainControllers,
    string? ServiceAccountUserName,
    bool HasServiceAccountPassword,
    bool PowerShellHealthEnabled,
    int PowerShellTimeoutSeconds,
    DateTime? LastValidatedAt,
    string? LastValidationStatus,
    string? LastValidationMessage,
    AdManagementNotificationSettingsResponse NotificationSettings);
