#!/usr/bin/env python3
"""Read the 8 legacy CSV exports and emit ONE self-contained SQL file that loads
them straight into the ITAdmin license tables (UUID PKs, enum member names,
request items aggregated to the unique (request_id, product_id) shape, legacy
assignments -> license_seat_assignments).

Usage:
    python3 build_import_sql.py /path/to/csv/dir  > itadmin_import.sql
"""
from __future__ import annotations

import csv
import sys
import uuid
from datetime import date
from pathlib import Path

TODAY = date(2026, 9, 7)
IMPORT_MARKER = "legacy-import"


def q(value: str | None) -> str:
    if value is None or value == "":
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def qdate(value: str | None) -> str:
    if not value:
        return "NULL"
    return "'" + value[:10] + "'"


def qts(value: str | None) -> str:
    if not value:
        return "NULL"
    return "'" + value + "'"


def read_csv(path: Path) -> list[dict]:
    """Read a CSV. The legacy export wrote the literal text 'NULL' for empty
    values, so normalise those (and whitespace-only) to '' up front."""
    with path.open(newline="", encoding="utf-8-sig") as fh:
        rows = list(csv.DictReader(fh))
    for row in rows:
        for key, value in list(row.items()):
            if value is None or value.strip() == "" or value.strip() == "NULL":
                row[key] = ""
    return rows


def main() -> None:
    src = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    companies = read_csv(src / "companies.csv")
    applications = read_csv(src / "applications.csv")
    purchases = read_csv(src / "purchases.csv")
    purchase_apps = read_csv(src / "purchase_applications.csv")
    assignments = read_csv(src / "license_assignments.csv")
    requests = read_csv(src / "license_requests.csv")
    request_items = read_csv(src / "license_request_items.csv")
    request_users = read_csv(src / "license_request_users.csv")

    company_by_id = {r["id"]: r for r in companies}
    request_by_id = {r["id"]: r for r in requests}

    cat_id = str(uuid.uuid4())
    map_product = {r["id"]: str(uuid.uuid4()) for r in applications}
    map_company = {r["id"]: str(uuid.uuid4()) for r in companies}
    map_purchase = {r["id"]: str(uuid.uuid4()) for r in purchases}
    map_package = {r["id"]: str(uuid.uuid4()) for r in purchase_apps}
    map_assignment = {r["id"]: str(uuid.uuid4()) for r in assignments}
    map_request = {r["id"]: str(uuid.uuid4()) for r in requests}

    warnings: list[str] = []
    out: list[str] = []
    w = out.append

    w("-- =========================================================================")
    w("-- ITAdmin - legacy License Management import (self-contained)")
    w("-- Generated by build_import_sql.py. Run once in pgAdmin Query Tool.")
    w("-- Requires migration 20260907122312_AddLicenseSeatAssignments or later.")
    w("-- Every row carries created_by = 'legacy-import' (see 99_rollback.sql).")
    w("-- =========================================================================")
    w("BEGIN;")
    w("")
    w("DO $$ BEGIN")
    w("  IF EXISTS (SELECT 1 FROM licensed_products WHERE created_by = 'legacy-import')")
    w("     OR EXISTS (SELECT 1 FROM license_companies WHERE created_by = 'legacy-import') THEN")
    w("    RAISE EXCEPTION 'legacy-import rows already exist - run 99_rollback.sql first';")
    w("  END IF;")
    w("END $$;")
    w("")

    # 1. category
    w("-- 1. category ---------------------------------------------------------------")
    w("INSERT INTO license_product_categories (id, name, description, is_active, created_at, created_by) VALUES")
    w(f"  ({q(cat_id)}, 'İçe Aktarılan', 'Eski lisans uygulamasından aktarılan ürünler', TRUE, now(), '{IMPORT_MARKER}');")
    w("")

    # 2. products
    w("-- 2. products (applications) ---------------------------------------------")
    rows = []
    for r in applications:
        rows.append(
            f"  ({q(map_product[r['id']])}, {q((r['name'] or '(isimsiz ürün)')[:200])}, "
            f"{q((r['brand'] or '')[:200] or None)}, {q(cat_id)}, {q('legacy application id: ' + r['id'])}, "
            f"TRUE, {qts(r.get('created_at'))}, '{IMPORT_MARKER}', {qts(r.get('updated_at'))}, "
            f"{('NULL' if not r.get('updated_at') else q(IMPORT_MARKER))})"
        )
    w("INSERT INTO licensed_products (id, name, brand, category_id, description, is_active, created_at, created_by, updated_at, updated_by) VALUES")
    w(",\n".join(rows) + ";")
    w("")

    # 3. companies
    w("-- 3. companies ---------------------------------------------------------------")
    rows = []
    for r in companies:
        rows.append(
            f"  ({q(map_company[r['id']])}, {q((r['name'] or '(isimsiz firma)').strip()[:200])}, "
            f"{q((r.get('phone') or '').strip()[:50] or None)}, {q((r.get('email') or '').strip()[:250] or None)}, NULL, "
            f"{q((r.get('contact_person') or '').strip()[:200] or None)}, NULL, NULL, "
            f"{q('legacy company id: ' + r['id'])}, TRUE, {qts(r.get('created_at'))}, '{IMPORT_MARKER}', "
            f"{qts(r.get('updated_at'))}, {('NULL' if not r.get('updated_at') else q(IMPORT_MARKER))})"
        )
    w("INSERT INTO license_companies (id, name, phone, email, website, contact_person_name, contact_person_phone, contact_person_email, notes, is_active, created_at, created_by, updated_at, updated_by) VALUES")
    w(",\n".join(rows) + ";")
    w("")

    # 4. purchases
    w("-- 4. purchases -------------------------------------------------------------")
    ptype = {"1": "Tender", "3": "DirectPurchase"}
    rows = []
    for r in purchases:
        t = ptype.get(r["procurement_type"], "Other")
        num = (r.get("procurement_number") or "").strip() or None
        tender = num if t == "Tender" else None
        direct = num if t == "DirectPurchase" else None
        note = "legacy purchase id: " + r["id"]
        if t == "Other" and num:
            note += " / belge no: " + num
        rows.append(
            f"  ({q(map_purchase[r['id']])}, '{t}', {q((r['name'] or ('Satın alma ' + r['id']))[:300])}, NULL, "
            f"{qdate(r.get('purchase_date'))}, {q(tender)}, {q(direct)}, 'Active', {q(note)}, "
            f"{qts(r.get('created_at'))}, '{IMPORT_MARKER}', {qts(r.get('updated_at'))}, "
            f"{('NULL' if not r.get('updated_at') else q(IMPORT_MARKER))})"
        )
    w("INSERT INTO license_purchases (id, purchase_type, title, description, purchase_date, tender_number, direct_purchase_number, status, notes, created_at, created_by, updated_at, updated_by) VALUES")
    w(",\n".join(rows) + ";")
    w("")

    # 5. packages
    w("-- 5. packages (purchase_applications) ----------------------------------")
    ltype = {"1": "Perpetual", "2": "Subscription"}
    rows = []
    for r in purchase_apps:
        if r["purchase_id"] not in map_purchase or r["application_id"] not in map_product:
            warnings.append(f"package {r['id']}: missing purchase/application -> skipped")
            continue
        lt = ltype.get(r["license_type"], "Other")
        end_raw = (r.get("license_end_date") or "")
        end_d = end_raw[:10] if end_raw else None
        company = company_by_id.get(r.get("company_id") or "")
        notes = (r.get("license_detail") or "")
        if company:
            notes += ("\n" if notes else "") + "Tedarikçi: " + (company["name"] or "").strip()
        notes += ("\n" if notes else "") + "legacy purchase_application id: " + r["id"]
        try:
            qty = max(int(r.get("user_count") or 1), 1)
        except ValueError:
            qty = 1
        status = "Expired" if (end_d and date.fromisoformat(end_d) < TODAY) else "Active"
        rows.append(
            f"  ({q(map_package[r['id']])}, {q(map_purchase[r['purchase_id']])}, {q(map_product[r['application_id']])}, "
            f"'{lt}', {qty}, NULL, {qdate(end_raw)}, {str(r['license_type'] == '1').upper()}, "
            f"{str(bool(end_d)).upper()}, NULL, NULL, NULL, NULL, NULL, {q(notes[:4000] or None)}, TRUE, '{status}', "
            f"{qts(r.get('created_at'))}, '{IMPORT_MARKER}', {qts(r.get('updated_at'))}, "
            f"{('NULL' if not r.get('updated_at') else q(IMPORT_MARKER))})"
        )
    w("INSERT INTO license_packages (id, purchase_id, product_id, license_type, quantity, start_date, end_date, is_perpetual, renewal_required, renewal_date, serial_number, license_key, license_account_email, license_portal_url, license_notes, is_active, status, created_at, created_by, updated_at, updated_by) VALUES")
    w(",\n".join(rows) + ";")
    w("")

    # 6. seat assignments
    w("-- 6. seat assignments (license_assignments) --------------------------")
    rows = []
    for r in assignments:
        if r["purchase_application_id"] not in map_package:
            warnings.append(f"assignment {r['id']}: package {r['purchase_application_id']} not found -> skipped")
            continue
        email = (r.get("assigned_email") or "").strip() or None
        sam = email.split("@")[0] if email else None
        adate = (r.get("assigned_date") or "")[:10] or (r.get("created_at") or "")[:10] or TODAY.isoformat()
        note = (r.get("description") or "")
        note += ("\n" if note else "") + "legacy assignment id: " + r["id"]
        rows.append(
            f"  ({q(map_assignment[r['id']])}, {q(map_package[r['purchase_application_id']])}, NULL, "
            f"{q((r.get('assigned_user_name') or '(bilinmiyor)')[:200])}, {q((sam or '')[:100] or None)}, "
            f"{q((email or '')[:250] or None)}, {q((email or '')[:250] or None)}, "
            f"{q((r.get('assigned_user_tcno') or '').strip()[:20] or None)}, NULL, NULL, "
            f"'{adate}', NULL, 'Active', NULL, NULL, {q(note[:4000] or None)}, "
            f"{qts(r.get('created_at'))}, '{IMPORT_MARKER}', {qts(r.get('updated_at'))}, "
            f"{('NULL' if not r.get('updated_at') else q(IMPORT_MARKER))})"
        )
    w("INSERT INTO license_seat_assignments (id, package_id, ad_object_id, display_name, sam_account_name, user_principal_name, mail, national_id, department, title, assigned_date, released_date, status, replaces_assignment_id, source_request_item_id, note, created_at, created_by, updated_at, updated_by) VALUES")
    w(",\n".join(rows) + ";")
    w("")

    # 7. requests
    w("-- 7. requests -----------------------------------------------------------")
    src_map = {"1": "OfficialLetter", "2": "CorporateRequestSystem"}
    stat_map = {"1": "Pending", "2": "Draft", "3": "Fulfilled", "4": "InReview"}
    rows = []
    for r in requests:
        rdate = (r.get("request_date") or "")[:10] or (r.get("created_at") or "")[:10] or TODAY.isoformat()
        rows.append(
            f"  ({q(map_request[r['id']])}, '{src_map.get(r['source'], 'Other')}', '{rdate}', "
            f"{q((r.get('request_number') or '').strip()[:100] or None)}, NULL, NULL, "
            f"'Bilinmiyor (içe aktarıldı)', '', '', NULL, {q((r.get('description') or '').strip()[:4000] or None)}, "
            f"'{stat_map.get(r['status'], 'Pending')}', TRUE, {qts(r.get('created_at'))}, '{IMPORT_MARKER}', "
            f"{qts(r.get('updated_at'))}, {('NULL' if not r.get('updated_at') else q(IMPORT_MARKER))})"
        )
    w("INSERT INTO license_requests (id, request_source, request_date, external_request_number, ebys_number, ebys_date, requester_unit_display_name, requester_unit_distinguished_name, requester_unit_object_guid, requester_manager_name, description, status, is_active, created_at, created_by, updated_at, updated_by) VALUES")
    w(",\n".join(rows) + ";")
    w("")

    # 8. request items - aggregate by (request, product)
    w("-- 8. request items (aggregated by request+product) ------------------")
    groups: dict[tuple[str, str], dict] = {}
    for r in request_items:
        key = (r["license_request_id"], r["application_id"])
        g = groups.setdefault(key, {"qty": 0, "created_at": r.get("created_at"), "uuid": str(uuid.uuid4())})
        try:
            g["qty"] += int(r.get("quantity") or 1)
        except ValueError:
            g["qty"] += 1
        if r.get("created_at") and (not g["created_at"] or r["created_at"] < g["created_at"]):
            g["created_at"] = r["created_at"]
    legacy_item_to_group = {}
    for r in request_items:
        legacy_item_to_group[r["id"]] = groups[(r["license_request_id"], r["application_id"])]["uuid"]

    rows = []
    for (req_old, app_old), g in groups.items():
        if req_old not in map_request or app_old not in map_product:
            warnings.append(f"request item ({req_old},{app_old}): missing request/product -> skipped")
            continue
        req = request_by_id.get(req_old, {})
        item_status = "Fulfilled" if req.get("status") == "3" else "Pending"
        rows.append(
            f"  ({q(g['uuid'])}, {q(map_request[req_old])}, {q(map_product[app_old])}, {g['qty']}, NULL, 0, "
            f"'{item_status}', {qts(g['created_at'])}, '{IMPORT_MARKER}')"
        )
    w("INSERT INTO license_request_items (id, request_id, product_id, requested_quantity, approved_quantity, fulfilled_quantity, status, created_at, created_by) VALUES")
    w(",\n".join(rows) + ";")
    w("")

    # 9. request item users
    w("-- 9. request item users -----------------------------------------------")
    seen: set[tuple[str, str]] = set()
    rows = []
    for r in request_users:
        gid = legacy_item_to_group.get(r["license_request_item_id"])
        if not gid:
            warnings.append(f"request user {r['id']}: item {r['license_request_item_id']} not found -> skipped")
            continue
        tc = (r.get("user_tcno") or "").strip()
        ad_object = "legacy:" + (tc if tc else "row" + r["id"])
        if (gid, ad_object) in seen:
            continue
        seen.add((gid, ad_object))
        email = (r.get("email") or "").strip() or None
        sam = email.split("@")[0] if email else None
        # find owning request status via any legacy item in this group
        req_status = "Pending"
        for (req_old, app_old), g in groups.items():
            if g["uuid"] == gid:
                req_status = "Fulfilled" if request_by_id.get(req_old, {}).get("status") == "3" else "Pending"
                break
        rows.append(
            f"  ({q(str(uuid.uuid4()))}, {q(gid)}, {q(ad_object[:100])}, {q((sam or '')[:100] or None)}, "
            f"{q((email or '')[:250] or None)}, {q((r.get('user_name') or '(bilinmiyor)')[:200])}, NULL, NULL, "
            f"{q((email or '')[:250] or None)}, NULL, '{req_status}', {qts(r.get('created_at'))}, '{IMPORT_MARKER}')"
        )
    w("INSERT INTO license_request_item_users (id, request_item_id, ad_object_id, sam_account_name, user_principal_name, display_name, department, title, mail, phone, status, created_at, created_by) VALUES")
    w(",\n".join(rows) + ";")
    w("")

    w("DO $$ BEGIN RAISE NOTICE 'legacy-import inserted: % products, % companies, % purchases, % packages, % seats, % requests, % request-items, % request-users',")
    w(f"  {len(applications)}, {len(companies)}, {len(purchases)}, {len(map_package)}, "
      f"{len(assignments)}, {len(requests)}, {len(groups)}, {len(seen)};")
    w("END $$;")
    w("")
    for line in warnings:
        w("-- WARNING: " + line)
    if warnings:
        w("")
    w("COMMIT;")
    w("-- To undo everything this file inserted, run 99_rollback.sql.")

    sys.stdout.write("\n".join(out) + "\n")
    sys.stderr.write(f"{len(warnings)} warning(s); "
                     f"{len(map_package)} packages, {len(groups)} agg items, {len(seen)} users\n")


if __name__ == "__main__":
    main()
